### ISSUE TITLE
Not loading in wrath 

### ISSUE THREAD

**Issue by Hyperneps** [Arrenton/KHUnitFrames#2]
I put the addon into my addons folder ofc, and it does not want to load unless its supposed to be paired with another addon to read it?

**Comment by Arrenton** [comment]
What do you mean? It should be able to run independantly. I still use the addon, so I try to keep it running.
Do you have an error you can post, or screenshot?

**Comment by Hyperneps** [comment]
completely forgot to check this, but I put it in my addons folder for both wrath and classic era and it just never shows up on the addon list as if its not in the folder

**Comment by Arrenton** [comment]
Is the folder name KHUnitFrames-master? If so, rename it to remove '-master'.

Keep in mind that there are a few quirks with this addon, and there are no buff/debuff trackers for the target UI so you'd need to use weakauras for that.

I designed this for myself and got it to the point I was fine with how it was.

**Comment by Hyperneps** [comment]
oops had no idea i had to change the folder name it works and love it ty
